---
name: Generic PANOPTES Unit
location:
    name: Siding Spring Observatory
    latitude: -31.2749 # Degrees
    longitude: 149.0685 # Degrees
    elevation: 1165.0 # Meters
    utc_offset: -10.00 # Hours
    horizon: 40.0 # Degrees
    twilight_horizon: -18 # Degrees
    timezone: Australia/Sydney
directories:
    base: /var/panoptes
    images: images
    webcam: webcams
    data: data
    resources: POCS/resources/
    targets: POCS/resources/conf_files/targets
    mounts: POCS/resources/conf_files/mounts
scheduler:
    type: dispatch
    fields_file: simple.yaml
mount:
    brand: ioptron
    model: 30
    driver: ioptron
    port: /dev/ttyUSB0
    non_sidereal_available: True
pointing:
    threshold: 0.05
    exptime: 30
    max_iterations: 3
cameras:
    auto_detect: True
    primary: 14d3bd
    devices:
    -
        model: canon_gphoto2
    -
        model: canon_gphoto2
messaging:
    cmd_port: 6500
    msg_port: 6510
state_machine: simple_state_table
grav_wave:
    selection_criteria:
        name: observable_tonight
        max_tiles: 100
    fov:
        ra: 3.0
        dec: 2.0
    alert_pocs: True
email_parsers:
-
    type: ParseGravWaveEmail
    inputs:
        selection_criteria:
            name: 5_tiles
            max_tiles: 5
    subjects:
        -
            LVC_TEST
-
    type: ParseSupernovaEmail
    inputs:
        none: none
    subjects:
        -
            Supernova
-
    type: ParseGRBEmail
    inputs:
        none: none
    subjects:
        -
            GRB
